
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ES_CapDien
{

using System;
    using System.Collections.Generic;
    
public partial class Administrator_Menu
{

    public System.Guid MenuId { get; set; }

    public System.Guid ParentId { get; set; }

    public string Name { get; set; }

    public string Style { get; set; }

    public int Index { get; set; }

    public System.Guid PageId { get; set; }

    public bool ShowUp { get; set; }

}

}
