
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ES_CapDien
{

using System;
    using System.Collections.Generic;
    
public partial class Data
{

    public int Id { get; set; }

    public int Device_Id { get; set; }

    public string BTI { get; set; }

    public string BHU { get; set; }

    public string BTO { get; set; }

    public string BDR { get; set; }

    public string BFL { get; set; }

    public string BFR { get; set; }

    public string BPS { get; set; }

    public string BAV { get; set; }

    public string BAP { get; set; }

    public string BAC { get; set; }

    public string BAF { get; set; }

    public string BV1 { get; set; }

    public string BC1 { get; set; }

    public string BT1 { get; set; }

    public string BV2 { get; set; }

    public string BC2 { get; set; }

    public string BT2 { get; set; }

    public string BSE { get; set; }

    public string BA1 { get; set; }

    public string BB1 { get; set; }

    public string BA2 { get; set; }

    public string BB2 { get; set; }

    public string BA3 { get; set; }

    public string BB3 { get; set; }

    public string BA4 { get; set; }

    public string BB4 { get; set; }

    public string BFA { get; set; }

    public string BFD { get; set; }

    public string BPW { get; set; }

    public Nullable<bool> IsSEQ { get; set; }

    public Nullable<System.DateTime> TimeSend { get; set; }

    public string BWS { get; set; }

}

}
