
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ES_CapDien
{

using System;
    using System.Collections.Generic;
    
public partial class DataAlarm
{

    public int Id { get; set; }

    public int Device_Id { get; set; }

    public string AMATI { get; set; }

    public string AMIHU { get; set; }

    public string AMADR { get; set; }

    public string AMAFL { get; set; }

    public string AMAFR { get; set; }

    public string AMIPS { get; set; }

    public string AMIAL { get; set; }

    public string AMIAH { get; set; }

    public string AMIAP { get; set; }

    public string AMIAC { get; set; }

    public string AMIGN { get; set; }

    public string AMIAR { get; set; }

    public string AMIL1 { get; set; }

    public string AMIH1 { get; set; }

    public string AMIT1 { get; set; }

    public string AMIL2 { get; set; }

    public string AMIH2 { get; set; }

    public string AMIT2 { get; set; }

    public System.DateTime TimeSend { get; set; }

}

}
