
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ES_CapDien
{

using System;
    using System.Collections.Generic;
    
public partial class Device
{

    public int Id { get; set; }

    public Nullable<int> Group_Id { get; set; }

    public int Site_Id { get; set; }

    public string Serial { get; set; }

    public Nullable<System.DateTime> CreateDay { get; set; }

    public Nullable<System.DateTime> UpdateDay { get; set; }

    public Nullable<int> CreateBy { get; set; }

    public Nullable<int> UpdateBy { get; set; }

    public string Off_Sns_after { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<System.DateTime> LastData { get; set; }

    public int Area_Id { get; set; }

    public Nullable<bool> IsAlarm { get; set; }

}

}
