
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ES_CapDien
{

using System;
    using System.Collections.Generic;
    
public partial class Observation
{

    public int Id { get; set; }

    public Nullable<bool> Noti_Alarm { get; set; }

    public string Name { get; set; }

    public string Code { get; set; }

    public Nullable<System.DateTime> CreateDay { get; set; }

    public Nullable<System.DateTime> UpdateDay { get; set; }

    public string Low_Value { get; set; }

    public string Hight_Value { get; set; }

    public Nullable<bool> IsBieuDo { get; set; }

}

}
