
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ES_CapDien
{

using System;
    using System.Collections.Generic;
    
public partial class RegisterSMS
{

    public int Id { get; set; }

    public string DanhSachSDT { get; set; }

    public string CodeObservation { get; set; }

    public Nullable<System.DateTime> DateCreate { get; set; }

    public Nullable<System.DateTime> DateSend { get; set; }

    public Nullable<int> DeviceId { get; set; }

    public Nullable<int> GroupId { get; set; }

    public Nullable<bool> IsAll { get; set; }

    public Nullable<int> SMSServerId { get; set; }

    public Nullable<int> UserCreate { get; set; }

    public Nullable<int> UserUpdate { get; set; }

}

}
