
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ES_CapDien
{

using System;
    using System.Collections.Generic;
    
public partial class SiteAdminLog
{

    public int ID { get; set; }

    public Nullable<int> UserID { get; set; }

    public Nullable<int> NewID { get; set; }

    public Nullable<System.DateTime> dateCreate { get; set; }

    public string IPAdressAccess { get; set; }

    public string Location { get; set; }

    public string SiteUrl { get; set; }

    public string Devices { get; set; }

    public string Browser { get; set; }

}

}
