
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ES_CapDien
{

using System;
    using System.Collections.Generic;
    
public partial class UserProfile
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public UserProfile()
    {

        this.Administrator_Notifications = new HashSet<Administrator_Notifications>();

        this.webpages_UsersInRoles = new HashSet<webpages_UsersInRoles>();

    }


    public int UserId { get; set; }

    public string UserName { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string SkypeID { get; set; }

    public string CompanyName { get; set; }

    public string Address { get; set; }

    public Nullable<int> GenderId { get; set; }

    public string CmisUserType { get; set; }

    public Nullable<int> Group_Id { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Administrator_Notifications> Administrator_Notifications { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<webpages_UsersInRoles> webpages_UsersInRoles { get; set; }

}

}
