
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ES_CapDien
{

using System;
    using System.Collections.Generic;
    
public partial class UserWebsite_Category
{

    public int Websites_Users_ID { get; set; }

    public int Category_ID { get; set; }

    public int Id { get; set; }

}

}
